[build]
  # Run build script to copy static files to public directory
  command = "node build.js"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  # Useful when running Netlify Dev locally
  command = "npm start"
  port = 8888
