services:
  - type: web
    name: phone
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: https://phone-4hza.onrender.com
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://trcbyqdfgnlaesixhorz.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: COINBASE_API_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
